export {default as Home} from './Home'
export {default as Webb} from './Webb'
export {default as Hubble} from './Hubble'
export {default as Apod} from './Apod'
export {default as Spacex} from './Spacex'
export {default as News} from './News'
export {default as Landing} from './Landing'
